pipeline {
    //These are pre-build sections
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 90, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    // parameters {
    //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    //     text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
    //     booleanParam(name: 'DEPLOY', defaultValue: false, description: 'Toggle this value')
    //     choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
    //     password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    // }
    // This is build section
    stages {
        stage('init') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform init
                        """
                    }
                }
            }
        }
        stage('Plan') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
               script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Parallel Trigger'){
            parallel {
                stage('Trigger bastion'){
                    steps {
                        script {
                            build job: '20-bastion',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('Trigger SgRules'){
                    steps {
                        script {
                            build job: '30-sg-rules',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('Trigger ECR'){
                    steps {
                        script {
                            build job: '40-ecr',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('Trigger ACM'){
                    steps {
                        script {
                            build job: '70-acm',
                                wait: false, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
                stage('Trigger EKS'){
                    steps {
                        script {
                            build job: '90-eks',
                                wait: true, // Wait for completion
                                propagate: false // Propagate status
                        }
                    }
                }
            }
        }
        stage('Trigger ALB'){
            steps {
                script {
                    build job: '80-frontend-alb',
                        wait: false, // Wait for completion
                        propagate: false // Propagate status
                }
            }
        }
    }
    post{
        always{
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo ' I will run if failure'
        }
        aborted{
            echo 'pipeline is aborted'
        }
    }
}